import numpy as np
import matplotlib.pyplot as plt

def generate_orthogonal_matrix(d):
    """
    Generate a random d x d orthogonal matrix using QR decomposition.
    
    This creates a random rotation/reflection matrix that preserves lengths.
    """
    # Generate random matrix with standard normal entries
    A = np.random.randn(d, d)
    # QR decomposition: Q is orthogonal, R is upper triangular
    Q, R = np.linalg.qr(A)
    return Q

def simulate_system(U, x0, T):
    """
    Simulate the linear dynamical system x_{i+1} = U * x_i for T time steps.
    
    Args:
        U: d x d orthogonal matrix (the system dynamics)
        x0: d-dimensional initial state
        T: number of time steps to simulate
    
    Returns:
        states: array of shape (T+1, d) containing [x0, x1, ..., xT]
                This is the TRUE trajectory generated by U
    """
    d = len(x0)
    states = np.zeros((T + 1, d))
    states[0] = x0
    
    # Apply U repeatedly to generate the sequence
    for i in range(T):
        states[i + 1] = U @ states[i]
    
    return states

def llse_predict(states, i):
    """
    LLSE predictor: x̂_{i+1} = X_out @ X_in† @ x_i
    
    This implements equation (2) from the problem.
    We use past observations to learn the dynamics and predict the next state.
    
    Args:
        states: array containing x0, x1, ..., x_i (the observed history)
        i: current time step
    
    Returns:
        x̂_{i+1}: predicted next state (or None if i=0)
    """
    if i == 0:
        # Can't predict at i=0 (no history to learn from)
        return None
    
    # X_in = [x0, x1, ..., x_{i-1}]  - these are our "inputs"
    # Shape: (d, i) - each column is a past state
    X_in = states[:i].T
    
    # X_out = [x1, x2, ..., x_i]  - these are our "outputs" (one step ahead)
    # Shape: (d, i) - each column is the next state after corresponding X_in column
    X_out = states[1:i+1].T
    
    # Current state we want to predict from
    x_i = states[i]
    
    # Compute pseudoinverse of X_in
    # This finds the "best" way to represent x_i in terms of past states
    X_in_pinv = np.linalg.pinv(X_in)
    
    # Make prediction using the learned pattern
    # X_in_pinv @ x_i finds coefficients, X_out applies the "one step forward" pattern
    x_hat = X_out @ X_in_pinv @ x_i
    
    return x_hat

def compute_squared_error(x_true, x_pred):
    """
    Compute squared L2 error: ||x_true - x_pred||²
    
    This measures how far off our prediction was.
    """
    if x_pred is None:
        return np.nan
    return np.sum((x_true - x_pred) ** 2)

def analytical_error(d, time_steps):
    """
    Compute the theoretical expected squared error from Problem 3.
    
    Theory says: E[error at step i] = max(0, d - i)
    - For i < d: error = d - i (not enough data to learn all dimensions)
    - For i >= d: error = 0 (have enough data to learn U perfectly)
    
    Args:
        d: dimension of the system
        time_steps: array of time step values
    
    Returns:
        analytical_errors: expected error at each time step
    """
    return np.maximum(0, d - time_steps)

def run_simulation(d, n_trajectories=1000, T=20):
    """
    Run full simulation for given dimension d.
    
    For ONE system U, we test it with many different initial conditions
    to see how well the LLSE predictor works on average.
    
    Args:
        d: dimension of the system
        n_trajectories: number of different initial states to try
        T: number of time steps
    
    Returns:
        all_errors: full array of errors (n_trajectories x T+1)
                   Each row is one trajectory, each column is one time step
    """
    # Generate ONE orthogonal matrix for this dimension
    # This is our "true system" that we'll test the predictor on
    U = generate_orthogonal_matrix(d)
    
    # Store errors for all trajectories
    # Shape: (n_trajectories, T+1)
    all_errors = np.zeros((n_trajectories, T + 1))
    
    print(f"Running {n_trajectories} trajectories for d={d}...")
    
    for traj in range(n_trajectories):
        # Show progress every 100 trajectories
        if (traj + 1) % 100 == 0:
            print(f"  Completed {traj + 1}/{n_trajectories} trajectories")
        
        # Generate random initial state x0 ~ N(0, I_d)
        x0 = np.random.randn(d)
        
        # Simulate the TRUE system using U
        # This gives us the ground truth: [x0, x1, x2, ..., xT]
        states = simulate_system(U, x0, T)
        
        # Now PRETEND we don't know U
        # Try to predict each x_{i+1} using only past observations
        for i in range(T):
            # Predict x_{i+1} using only [x0, ..., xi]
            x_pred = llse_predict(states, i)
            
            # Compare to the TRUE x_{i+1} (from our simulation)
            x_true = states[i + 1]
            
            # Compute squared prediction error
            error = compute_squared_error(x_true, x_pred)
            all_errors[traj, i + 1] = error
    
    return all_errors

def plot_results(results_dict, dimensions, T):
    """
    Create comprehensive plots of the LLSE predictor performance.
    
    Makes two plots:
    1. Linear plot with mean, std, and analytical error
    2. Log-linear plot with median, percentiles, and mean
    """
    time_steps = np.arange(T + 1)
    
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
    
    for d in dimensions:
        all_errors = results_dict[d]['all_errors']
        n_traj = all_errors.shape[0]
        
        # Compute statistics across trajectories (axis=0)
        mean_errors = np.nanmean(all_errors, axis=0)  # Average error at each time
        std_errors = np.nanstd(all_errors, axis=0)    # Standard deviation at each time
        
        # Plot mean with standard deviation as error bars
        ax1.errorbar(time_steps, mean_errors, yerr=std_errors, 
                    marker='o', label=f'd={d} (n={n_traj})', 
                    linewidth=2, capsize=5, alpha=0.8)
        
        # Plot analytical (theoretical) expected error
        theory = analytical_error(d, time_steps)
        ax1.plot(time_steps, theory, '--', linewidth=2, 
                label=f'd={d} (theory)', alpha=0.7)
    
    ax1.set_xlabel('Time Step i', fontsize=12)
    ax1.set_ylabel('Squared Error', fontsize=12)
    ax1.set_title('LLSE Predictor: Mean Error ± Std Dev vs Theory', fontsize=14)
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    
    for d in dimensions:
        all_errors = results_dict[d]['all_errors']
        n_traj = all_errors.shape[0]
        
        # Compute median and percentiles across trajectories
        median_errors = np.nanmedian(all_errors, axis=0)  # Median error at each time
        p25 = np.nanpercentile(all_errors, 25, axis=0)    # 25th percentile
        p75 = np.nanpercentile(all_errors, 75, axis=0)    # 75th percentile
        mean_errors = np.nanmean(all_errors, axis=0)      # Mean for comparison
        
        # Plot median with IQR (interquartile range) as error bars
        # Error bars go from 25th to 75th percentile
        ax2.errorbar(time_steps, median_errors, 
                    yerr=[median_errors - p25, p75 - median_errors],
                    marker='o', label=f'd={d} median (n={n_traj})', 
                    linewidth=2, capsize=5, alpha=0.8)
        
        # Plot mean on the same graph for comparison
        ax2.plot(time_steps, mean_errors, '--', marker='s',
                label=f'd={d} mean', linewidth=2, alpha=0.7)
    
    ax2.set_xlabel('Time Step i', fontsize=12)
    ax2.set_ylabel('Squared Error (log scale)', fontsize=12)
    ax2.set_title('LLSE Predictor: Median (IQR) vs Mean', fontsize=14)
    ax2.set_yscale('log')  # Log scale on y-axis
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.show()

def analyze_results(results_dict, dimensions, T):
    """
    Print detailed analysis of the results to answer the questions.
    """
    print("\n" + "="*70)
    print("ANALYSIS OF RESULTS")
    print("="*70)
    
    time_steps = np.arange(T + 1)
    
    for d in dimensions:
        all_errors = results_dict[d]['all_errors']
        n_traj = all_errors.shape[0]
        
        print(f"\n--- Dimension d={d} (n={n_traj} trajectories) ---")
        
        # Compute statistics
        mean_errors = np.nanmean(all_errors, axis=0)
        std_errors = np.nanstd(all_errors, axis=0)
        median_errors = np.nanmedian(all_errors, axis=0)
        theory = analytical_error(d, time_steps)
        
        # Check a few key time steps
        print(f"\nTime step i=1:")
        print(f"  Simulated mean: {mean_errors[1]:.3f} ± {std_errors[1]:.3f}")
        print(f"  Theory: {theory[1]:.3f}")
        print(f"  Within 1 std dev? {abs(mean_errors[1] - theory[1]) <= std_errors[1]}")
        
        print(f"\nTime step i={d} (critical point where theory hits 0):")
        print(f"  Simulated mean: {mean_errors[d]:.3f} ± {std_errors[d]:.3f}")
        print(f"  Theory: {theory[d]:.3f}")
        print(f"  Within 1 std dev? {abs(mean_errors[d] - theory[d]) <= std_errors[d]}")
        
        print(f"\nTime step i={T}:")
        print(f"  Simulated mean: {mean_errors[T]:.3f} ± {std_errors[T]:.3f}")
        print(f"  Theory: {theory[T]:.3f}")
        
        # Compare mean vs median
        print(f"\n--- Mean vs Median Comparison ---")
        # Look at early time steps where error is high
        early_steps = range(1, min(d+1, T+1))
        for i in early_steps:
            if mean_errors[i] > median_errors[i]:
                print(f"  Step {i}: Mean ({mean_errors[i]:.3f}) > Median ({median_errors[i]:.3f})")
            else:
                print(f"  Step {i}: Mean ({mean_errors[i]:.3f}) ≤ Median ({median_errors[i]:.3f})")
        
        print(f"\nWhy is mean often > median?")
        print(f"  The error distribution is RIGHT-SKEWED (has outliers on the high end).")
        print(f"  Occasionally the predictor makes very bad predictions (large errors),")
        print(f"  which pull the mean up, but don't affect the median as much.")



# Run simulations for d = 2, 5, 10
dimensions = [2, 5, 10]
T = 20  # 20 time steps

# First run with n=1000
print("\n" + "="*70)
print("RUNNING WITH n=1000 TRAJECTORIES")
print("="*70)

results_1000 = {}
for d in dimensions:
    all_errors = run_simulation(d, n_trajectories=1000, T=T)
    results_1000[d] = {'all_errors': all_errors}

plot_results(results_1000, dimensions, T)
analyze_results(results_1000, dimensions, T)

# Now run with n=10000 to see if error bars shrink
print("\n" + "="*70)
print("RUNNING WITH n=10000 TRAJECTORIES")
print("="*70)
print("This will take longer (~10x more time)...")

# Run only for d=5 to save time (you can add others if desired)
results_10000 = {}
d = 5
all_errors = run_simulation(d, n_trajectories=10000, T=T)
results_10000[d] = {'all_errors': all_errors}

# Plot comparison: n=1000 vs n=10000
print("\n" + "="*70)
print("COMPARING n=1000 vs n=10000")
print("="*70)

fig, ax = plt.subplots(1, 1, figsize=(10, 6))
time_steps = np.arange(T + 1)

# Plot n=1000 results
all_errors_1000 = results_1000[d]['all_errors']
mean_1000 = np.nanmean(all_errors_1000, axis=0)
std_1000 = np.nanstd(all_errors_1000, axis=0)

ax.errorbar(time_steps, mean_1000, yerr=std_1000,
           marker='o', label=f'd={d}, n=1000',
           linewidth=2, capsize=5, alpha=0.8)

# Plot n=10000 results
all_errors_10000 = results_10000[d]['all_errors']
mean_10000 = np.nanmean(all_errors_10000, axis=0)
std_10000 = np.nanstd(all_errors_10000, axis=0)

ax.errorbar(time_steps, mean_10000, yerr=std_10000,
           marker='s', label=f'd={d}, n=10000',
           linewidth=2, capsize=5, alpha=0.8)

# Plot theory
theory = analytical_error(d, time_steps)
ax.plot(time_steps, theory, '--', linewidth=3,
       label='Theory', alpha=0.9, color='black')

ax.set_xlabel('Time Step i', fontsize=12)
ax.set_ylabel('Squared Error', fontsize=12)
ax.set_title(f'd={d}: Effect of Sample Size on Error Bars', fontsize=14)
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

print(f"\nError bar comparison for d={d}:")
print(f"  At i=1:")
print(f"    n=1000:  std = {std_1000[1]:.3f}")
print(f"    n=10000: std = {std_10000[1]:.3f}")
print(f"    Ratio: {std_1000[1]/std_10000[1]:.2f}x")
print(f"\n  Theory predicts ratio ≈ √10 ≈ 3.16x")
print(f"  More samples → smaller error bars → more precise estimate!")